import { Award, BookOpen, Check, Clock3, Globe2, PlayCircle, Star, Users } from "lucide-react";
import { getCourseBySlug } from "@/lib/services/course-service";
import { Button } from "@/components/ui/button";
import { Footer } from "@/components/layout/footer";

export default async function CourseDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const course = await getCourseBySlug(slug);
  return <>
    <section className="course-detail-hero"><div className="container course-detail-grid"><div><div style={{display:"flex",gap:8}}><span className="level-badge">{course.level}</span><span>{course.category}</span></div><h1>{course.title}</h1><p>{course.description} Yapılandırılmış dersler, özgün örnekler, interaktif alıştırmalar ve düzenli performans takibiyle temel iletişim becerilerini geliştir.</p><div className="rating-row"><span><Star size={17} fill="currentColor"/> {course.rating} · {course.reviews} değerlendirme</span><span><Users size={17}/> {course.students} öğrenci</span><span><Globe2 size={17}/> Türkçe anlatım · Almanca içerik</span></div><p style={{fontSize:14}}>Hazırlayan: Deutschimo Akademi · Son güncelleme: Temmuz 2026</p></div><div className="enroll-card"><div className="enroll-cover"><PlayCircle size={64}/></div><div className="enroll-body"><span className="eyebrow">{course.access}</span><h2 style={{color:"var(--heading)"}}>Programa hemen başla</h2><Button href="/learn/kendini-tanitmak">Kursa Başla</Button><Button href="/learn/kendini-tanitmak" variant="secondary">Ücretsiz Ön İzle</Button><ul className="check-list"><li><Clock3 size={18}/>{course.duration} yapılandırılmış program</li><li><BookOpen size={18}/>{course.lessons} ders ve uygulama</li><li><Award size={18}/>Tamamlama sertifikası</li></ul></div></div></div></section>
    <div className="container detail-layout"><div className="detail-content"><section className="card"><h2>Bu kursta neler öğreneceksin?</h2><div className="outcomes">{["Selamlaşma ve vedalaşma ifadelerini kullanmak","Kendini isim, ülke, şehir ve eğitim bilgisiyle tanıtmak","Basit sorular sormak ve kısa cevaplar vermek","sein fiilini kişi zamirleriyle doğru çekmek","Temel dinleme metinlerinde ana bilgiyi seçmek","Kısa tanışma diyaloğu yazmak ve seslendirmek"].map(x=><div className="outcome" key={x}><Check size={18}/><span>{x}</span></div>)}</div></section><section className="card"><h2>Kurs açıklaması</h2><p>Bu program Almancaya yeni başlayan kullanıcılar için tasarlanmıştır. Her ders hedef, konu anlatımı, özgün örnekler, kontrollü alıştırma, mini quiz ve sonraki ders önerisinden oluşur. Türkçe destek başlangıç seviyesinde daha yoğundur; Almanca kullanım oranı program boyunca kademeli olarak artar.</p></section><section><h2 style={{color:"var(--heading)"}}>Kurs müfredatı</h2><div className="curriculum"><details open><summary>Ünite 1: Tanışma ve Selamlaşma · 7 ders</summary><ul><li>Selamlaşma ifadeleri · Okuma</li><li>Kendini tanıtmak · Video</li><li>sein fiili · Gramer</li><li>Kişi zamirleri · Alıştırma</li><li>Kelime çalışması · Flashcard</li><li>Dinleme alıştırması</li><li>Ünite testi</li></ul></details><details><summary>Ünite 2: Aile ve Meslekler · 8 ders</summary><ul><li>Aile üyeleri</li><li>Meslekler</li><li>İyelik zamirleri</li><li>Ünite görevi</li></ul></details><details><summary>Ünite 3: Günlük Hayat · 8 ders</summary><ul><li>Saatler ve günlük rutin</li><li>Ayrılabilen fiiller</li><li>Günlük plan yazma</li></ul></details></div></section><section className="card"><h2>Kimler için uygun?</h2><p>Almancaya sıfırdan başlayanlar, üniversite hazırlık öğrencileri, Almanya'da eğitim veya çalışma hedefi olanlar ve temel bilgilerini sistemli biçimde yeniden kurmak isteyenler.</p></section></div><aside></aside></div><Footer/>
  </>;
}
