"use client";
import { FormEvent, useState } from "react";
import { signOut } from "next-auth/react";
import { Download, KeyRound, Trash2 } from "lucide-react";

export function AccountSecurityPanel({ hasPassword }: { hasPassword: boolean }) {
  const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const [passwords,setPasswords]=useState({currentPassword:"",newPassword:""});
  const [deletion,setDeletion]=useState({confirmation:"",password:""});
  async function changePassword(e:FormEvent){e.preventDefault();setError("");setMessage("");const r=await fetch("/api/account/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(passwords)});const p=await r.json();if(!r.ok){setError(p.error||"Şifre değiştirilemedi.");return;}setMessage("Şifren değiştirildi. Güvenlik için diğer oturumlar kapatıldı.");setPasswords({currentPassword:"",newPassword:""});}
  async function deleteAccount(){if(!window.confirm("Hesabın ve bütün öğrenme verilerin kalıcı olarak silinecek. Bu işlem geri alınamaz."))return;setError("");const r=await fetch("/api/account/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(deletion)});const p=await r.json();if(!r.ok){setError(p.error||"Hesap silinemedi.");return;}await signOut({callbackUrl:"/"});}
  return <section className="panel account-security-panel"><h2>Güvenlik ve verilerim</h2><p>Şifreni yönetebilir, verilerinin bir kopyasını indirebilir veya hesabını kalıcı olarak silebilirsin.</p>{message?<div className="auth-message auth-success">{message}</div>:null}{error?<div className="auth-message auth-error">{error}</div>:null}{hasPassword?<form onSubmit={changePassword} className="security-form"><h3><KeyRound size={19}/> Şifre değiştir</h3><label className="field"><span>Mevcut şifre</span><input type="password" value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label className="field"><span>Yeni şifre</span><input type="password" value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/><small>En az 12 karakter; büyük/küçük harf, rakam ve özel karakter.</small></label><button className="button button-secondary">Şifreyi Güncelle</button></form>:null}<div className="account-data-actions"><a className="button button-secondary" href="/api/account/export"><Download size={17}/> Verilerimi İndir</a></div><div className="danger-zone"><h3><Trash2 size={19}/> Hesabı kalıcı olarak sil</h3><p>Bu işlem profilini, ilerlemeni, sınav sonuçlarını ve öğrenme geçmişini geri döndürülemez biçimde siler.</p><label className="field"><span>Onay için “HESABIMI SİL” yaz</span><input value={deletion.confirmation} onChange={e=>setDeletion({...deletion,confirmation:e.target.value})}/></label>{hasPassword?<label className="field"><span>Şifren</span><input type="password" value={deletion.password} onChange={e=>setDeletion({...deletion,password:e.target.value})}/></label>:null}<button type="button" className="button button-danger" onClick={deleteAccount}>Hesabımı ve Verilerimi Sil</button></div></section>;
}
