"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Activity, BookOpenText, CheckCircle2, Dumbbell, Users } from "lucide-react";
import { courses } from "@/data/courses";
import { totalExerciseCounts } from "@/data/exercises";
import { unitCounts } from "@/data/units";

type Stats={users:number;activeUsers:number;newUsers:number;completedUnits:number;activityEvents:number};
export function AdminOverview(){const[stats,setStats]=useState<Stats>({users:0,activeUsers:0,newUsers:0,completedUnits:0,activityEvents:0});useEffect(()=>{fetch("/api/admin/stats",{cache:"no-store"}).then((r)=>r.json()).then(setStats).catch(()=>undefined)},[]);const totalUnits=Object.values(unitCounts).reduce((sum,count)=>sum+count,0);const totalExercises=Object.values(totalExerciseCounts).reduce((sum,count)=>sum+count,0);return <><div className="stats-grid"><AdminStat icon={<Users/>} label="Kayıtlı kullanıcı" value={String(stats.users)} note={`${stats.newUsers} yeni kayıt · son 30 gün`}/><AdminStat icon={<Activity/>} label="Aktif kullanıcı" value={String(stats.activeUsers)} note="Son 30 günde giriş yapan"/><AdminStat icon={<BookOpenText/>} label="Toplam ünite" value={String(totalUnits)} note="A1, A2, B1 ve B2"/><AdminStat icon={<Dumbbell/>} label="Toplam alıştırma" value={String(totalExercises)} note="Yapılandırılmış içerik"/><AdminStat icon={<CheckCircle2/>} label="Tamamlanan ünite" value={String(stats.completedUnits)} note={`${stats.activityEvents} öğrenme etkinliği`}/></div><div className="admin-overview-grid"><section className="panel"><div className="section-head"><div><h2>İçerik sistemi</h2><p>Mevcut V10 içerikleri korunurken kullanıcı ve ilerleme katmanı artık sunucuda çalışır.</p></div><Link className="button button-primary" href="/admin/content">İçerikleri Yönet</Link></div><div className="admin-level-list">{courses.map((course)=><div key={course.id}><span className="level-badge">{course.level}</span><strong>{course.unitCount} ünite</strong><span>{totalExerciseCounts[course.level]} alıştırma</span></div>)}</div></section><section className="panel"><h2>Hızlı işlemler</h2><div className="quick-admin-actions"><Link href="/admin/users"><Users/>Gerçek kullanıcıları yönet</Link><Link href="/admin/content"><BookOpenText/>Ünite ve slaytları düzenle</Link><Link href="/courses"><Activity/>Öğrenci görünümünü aç</Link></div></section></div></>}
function AdminStat({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="stat-card"><div style={{display:"flex",justifyContent:"space-between",color:"var(--turquoise-dark)"}}><span>{label}</span>{icon}</div><strong>{value}</strong><span>{note}</span></article>}
